[build]
builder = "dockerfile"

[deploy]
startCommand = "python server.py --seed"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "ultima-pointage"
